services:
  app:
    image: 058264194030.dkr.ecr.us-east-2.amazonaws.com/planner-poc:latest
    restart: unless-stopped
    ports:
      - "9000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/up"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - sail
networks:
  sail:
    external: true
